-- 1: List all customers who have made purchases of more than $80.

SELECT 
    U.name, 
    U.email, 
    SUM(O.total_amount) AS total_spent
FROM 
    Users U
JOIN 
    Orders O ON U.user_id = O.user_id
GROUP BY 
    U.user_id
HAVING 
    total_spent > 80;


-- 2: Retrieve all orders placed in the last 280 days along with the customer name and email.

SELECT orders.order_id, users.name, users.email,  orders.order_date, orders.total_amount
FROM users
RIGHT JOIN orders on users.user_id = orders.user_id
WHERE orders.order_date >= (CURDATE() - INTERVAL 600 DAY);


-- 3: Find the average product price for each category

SELECT category, AVG(price) as avg_price 
FROM products
GROUP BY category;

-- 4. List all customers who have purchased a product from the category Electronics. 

SELECT DISTINCT u.name, u.email FROM users u
JOIN orders o ON o.user_id = u.user_id
JOIN orderdetails od ON o.order_id = od.order_id
JOIN products p ON p.product_id = od.product_id
WHERE p.category = 'Electronics';

-- 5. Find the total number of products sold and the total revenue generated for each product.

SELECT p.name as prod_name, SUM(od.quantity) as no_sold, SUM(od.quantity * p.price) as total_revenue
FROM orderdetails od
JOIN products p ON p.product_id = od.product_id
GROUP BY p.product_id

-- 6. Update the price of all products in the Books category, increasing it by 10%.

UPDATE products
SET price = price * 1.10
WHERE category = 'Books'

-- 7. Remove all orders that were placed before 2020.

DELETE FROM orders
WHERE order_date < '2020-01-01';

-- 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.

SELECT u.name as cust_name, p.name as prod_name, o.order_date, od.quantity
FROM users u
JOIN orders o ON o.user_id = u.user_id
JOIN orderdetails od ON o.order_id = od.order_id
JOIN products p ON p.product_id = od.product_id
WHERE order_date = '2024-05-01';

-- 9. Fetch all customers and the total number of orders they have placed.
SELECT u.name as cust_name, COUNT(o.order_id) total_orders
FROM users u
LEFT JOIN orders o ON o.user_id = u.user_id
GROUP BY u.user_id

-- 10. List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.


SELECT u.name as cust_name, u.email, p.name as prod_name, SUM(od.quantity) as tot_qty
FROM users u
JOIN orders o ON o.user_id = u.user_id
JOIN orderdetails od ON o.order_id = od.order_id
JOIN products p ON p.product_id = od.product_id
GROUP BY u.user_id, p.product_id
HAVING SUM(od.quantity)>1

-- 11. Find the total revenue generated by each category along with the category name.

SELECT p.category, SUM(od.quantity) as no_sold, SUM(od.quantity * p.price) as total_revenue
FROM orderdetails od
JOIN products p ON p.product_id = od.product_id
GROUP BY p.category

